export const CURRENCIES = [
  { code: 'AMD', name: 'Armenian Dram', symbol: '֏', country: 'AM', flag: '/assets/images/flags/am.png' },
  { code: 'USD', name: 'US Dollar', symbol: '$', country: 'US', flag: '/assets/images/flags/us.png' },
  { code: 'EUR', name: 'Euro', symbol: '€', country: 'EU', flag: '/assets/images/flags/de.png' },
  { code: 'GBP', name: 'British Pound', symbol: '£', country: 'GB', flag: '/assets/images/flags/gb.png' },
  { code: 'JPY', name: 'Japanese Yen', symbol: '¥', country: 'JP', flag: '/assets/images/flags/jp.png' },
  { code: 'CAD', name: 'Canadian Dollar', symbol: 'C$', country: 'CA', flag: '/assets/images/flags/ca.png' },
  { code: 'AUD', name: 'Australian Dollar', symbol: 'A$', country: 'AU', flag: '/assets/images/flags/au.png' },
  { code: 'CHF', name: 'Swiss Franc', symbol: 'CHF', country: 'CH', flag: '/assets/images/flags/ch.png' },
  { code: 'CNY', name: 'Chinese Yuan', symbol: '¥', country: 'CN', flag: '/assets/images/flags/cn.png' },
  { code: 'SEK', name: 'Swedish Krona', symbol: 'kr', country: 'SE', flag: '/assets/images/flags/se.png' },
  { code: 'NZD', name: 'New Zealand Dollar', symbol: 'NZ$', country: 'NZ', flag: '/assets/images/flags/nz.png' },
  { code: 'MXN', name: 'Mexican Peso', symbol: '$', country: 'MX', flag: '/assets/images/flags/mx.png' },
  { code: 'SGD', name: 'Singapore Dollar', symbol: 'S$', country: 'SG', flag: '/assets/images/flags/sg.png' },
  { code: 'HKD', name: 'Hong Kong Dollar', symbol: 'HK$', country: 'HK', flag: '/assets/images/flags/hk.png' },
  { code: 'NOK', name: 'Norwegian Krone', symbol: 'kr', country: 'NO', flag: '/assets/images/flags/no.png' },
  { code: 'TRY', name: 'Turkish Lira', symbol: '₺', country: 'TR', flag: '/assets/images/flags/tr.png' },
  { code: 'RUB', name: 'Russian Ruble', symbol: '₽', country: 'RU', flag: '/assets/images/flags/ru.png' },
  { code: 'INR', name: 'Indian Rupee', symbol: '₹', country: 'IN', flag: '/assets/images/flags/in.png' },
  { code: 'BRL', name: 'Brazilian Real', symbol: 'R$', country: 'BR', flag: '/assets/images/flags/br.png' },
  { code: 'ZAR', name: 'South African Rand', symbol: 'R', country: 'ZA', flag: '/assets/images/flags/za.png' },
  { code: 'KRW', name: 'South Korean Won', symbol: '₩', country: 'KR', flag: '/assets/images/flags/kr.png' },
  { code: 'DKK', name: 'Danish Krone', symbol: 'kr', country: 'DK', flag: '/assets/images/flags/dk.png' },
  { code: 'PLN', name: 'Polish Zloty', symbol: 'zł', country: 'PL', flag: '/assets/images/flags/pl.png' },
  { code: 'TWD', name: 'Taiwan Dollar', symbol: 'NT$', country: 'TW', flag: '/assets/images/flags/tw.png' },
  { code: 'THB', name: 'Thai Baht', symbol: '฿', country: 'TH', flag: '/assets/images/flags/th.png' },
  { code: 'MYR', name: 'Malaysian Ringgit', symbol: 'RM', country: 'MY', flag: '/assets/images/flags/my.png' },
  { code: 'PHP', name: 'Philippine Peso', symbol: '₱', country: 'PH', flag: '/assets/images/flags/ph.png' },
  { code: 'CZK', name: 'Czech Koruna', symbol: 'Kč', country: 'CZ', flag: '/assets/images/flags/cz.png' },
  { code: 'HUF', name: 'Hungarian Forint', symbol: 'Ft', country: 'HU', flag: '/assets/images/flags/hu.png' },
  { code: 'ILS', name: 'Palestinian Shekel', symbol: '₪', country: 'PS', flag: '/assets/images/flags/ps.png' },
  { code: 'CLP', name: 'Chilean Peso', symbol: '$', country: 'CL', flag: '/assets/images/flags/cl.png' },
  { code: 'PKR', name: 'Pakistani Rupee', symbol: '₨', country: 'PK', flag: '/assets/images/flags/pk.png' },
  { code: 'BGN', name: 'Bulgarian Lev', symbol: 'лв', country: 'BG', flag: '/assets/images/flags/bg.png' },
  { code: 'RON', name: 'Romanian Leu', symbol: 'lei', country: 'RO', flag: '/assets/images/flags/ro.png' },
  { code: 'HRK', name: 'Croatian Kuna', symbol: 'kn', country: 'HR', flag: '/assets/images/flags/hr.png' },
  { code: 'ISK', name: 'Icelandic Krona', symbol: 'kr', country: 'IS', flag: '/assets/images/flags/is.png' },
  { code: 'UAH', name: 'Ukrainian Hryvnia', symbol: '₴', country: 'UA', flag: '/assets/images/flags/ua.png' },
  { code: 'AED', name: 'UAE Dirham', symbol: 'د.إ', country: 'AE', flag: '/assets/images/flags/ae.png' },
  { code: 'SAR', name: 'Saudi Riyal', symbol: '﷼', country: 'SA', flag: '/assets/images/flags/sa.png' },
  { code: 'QAR', name: 'Qatari Riyal', symbol: '﷼', country: 'QA', flag: '/assets/images/flags/qa.png' },
  { code: 'KWD', name: 'Kuwaiti Dinar', symbol: 'د.ك', country: 'KW', flag: '/assets/images/flags/kw.png' },
  { code: 'BHD', name: 'Bahraini Dinar', symbol: 'د.ب', country: 'BH', flag: '/assets/images/flags/bh.png' },
  { code: 'OMR', name: 'Omani Rial', symbol: '﷼', country: 'OM', flag: '/assets/images/flags/om.png' },
  { code: 'JOD', name: 'Jordanian Dinar', symbol: 'د.ا', country: 'JO', flag: '/assets/images/flags/jo.png' },
  { code: 'LBP', name: 'Lebanese Pound', symbol: 'ل.ل', country: 'LB', flag: '/assets/images/flags/lb.png' },
  { code: 'EGP', name: 'Egyptian Pound', symbol: '£', country: 'EG', flag: '/assets/images/flags/eg.png' },
  { code: 'MAD', name: 'Moroccan Dirham', symbol: 'د.م.', country: 'MA', flag: '/assets/images/flags/ma.png' },
  { code: 'TND', name: 'Tunisian Dinar', symbol: 'د.ت', country: 'TN', flag: '/assets/images/flags/tn.png' },
  { code: 'DZD', name: 'Algerian Dinar', symbol: 'د.ج', country: 'DZ', flag: '/assets/images/flags/dz.png' },
  { code: 'LYD', name: 'Libyan Dinar', symbol: 'ل.د', country: 'LY', flag: '/assets/images/flags/ly.png' },
  { code: 'ETB', name: 'Ethiopian Birr', symbol: 'Br', country: 'ET', flag: '/assets/images/flags/et.png' },
  { code: 'KES', name: 'Kenyan Shilling', symbol: 'KSh', country: 'KE', flag: '/assets/images/flags/ke.png' },
  { code: 'UGX', name: 'Ugandan Shilling', symbol: 'USh', country: 'UG', flag: '/assets/images/flags/ug.png' },
  { code: 'TZS', name: 'Tanzanian Shilling', symbol: 'TSh', country: 'TZ', flag: '/assets/images/flags/tz.png' },
  { code: 'NGN', name: 'Nigerian Naira', symbol: '₦', country: 'NG', flag: '/assets/images/flags/ng.png' },
  { code: 'GHS', name: 'Ghanaian Cedi', symbol: '₵', country: 'GH', flag: '/assets/images/flags/gh.png' },
  { code: 'XOF', name: 'West African CFA Franc', symbol: 'CFA', country: 'XOF', flag: '/assets/images/flags/sn.png' },
  { code: 'XAF', name: 'Central African CFA Franc', symbol: 'FCFA', country: 'XAF', flag: '/assets/images/flags/cm.png' },
  { code: 'ARS', name: 'Argentine Peso', symbol: '$', country: 'AR', flag: '/assets/images/flags/ar.png' },
  { code: 'UYU', name: 'Uruguayan Peso', symbol: '$U', country: 'UY', flag: '/assets/images/flags/uy.png' },
  { code: 'BOB', name: 'Bolivian Boliviano', symbol: 'Bs', country: 'BO', flag: '/assets/images/flags/bo.png' },
  { code: 'PEN', name: 'Peruvian Sol', symbol: 'S/', country: 'PE', flag: '/assets/images/flags/pe.png' },
  { code: 'COP', name: 'Colombian Peso', symbol: '$', country: 'CO', flag: '/assets/images/flags/co.png' },
  { code: 'VES', name: 'Venezuelan Bolivar', symbol: 'Bs.S', country: 'VE', flag: '/assets/images/flags/ve.png' },
  { code: 'GTQ', name: 'Guatemalan Quetzal', symbol: 'Q', country: 'GT', flag: '/assets/images/flags/gt.png' },
  { code: 'HNL', name: 'Honduran Lempira', symbol: 'L', country: 'HN', flag: '/assets/images/flags/hn.png' },
  { code: 'NIO', name: 'Nicaraguan Cordoba', symbol: 'C$', country: 'NI', flag: '/assets/images/flags/ni.png' },
  { code: 'CRC', name: 'Costa Rican Colon', symbol: '₡', country: 'CR', flag: '/assets/images/flags/cr.png' },
  { code: 'PAB', name: 'Panamanian Balboa', symbol: 'B/.', country: 'PA', flag: '/assets/images/flags/pa.png' },
  { code: 'DOP', name: 'Dominican Peso', symbol: 'RD$', country: 'DO', flag: '/assets/images/flags/do.png' },
  { code: 'JMD', name: 'Jamaican Dollar', symbol: 'J$', country: 'JM', flag: '/assets/images/flags/jm.png' },
  { code: 'TTD', name: 'Trinidad and Tobago Dollar', symbol: 'TT$', country: 'TT', flag: '/assets/images/flags/tt.png' },
  { code: 'BBD', name: 'Barbadian Dollar', symbol: 'Bds$', country: 'BB', flag: '/assets/images/flags/bb.png' },
  { code: 'BZD', name: 'Belize Dollar', symbol: 'BZ$', country: 'BZ', flag: '/assets/images/flags/bz.png' },
  { code: 'XCD', name: 'East Caribbean Dollar', symbol: 'EC$', country: 'XCD', flag: '/assets/images/flags/ag.png' },
  { code: 'AWG', name: 'Aruban Florin', symbol: 'ƒ', country: 'AW', flag: '/assets/images/flags/aw.png' },
  { code: 'ANG', name: 'Netherlands Antillean Guilder', symbol: 'ƒ', country: 'AN', flag: '/assets/images/flags/nl.png' },
  { code: 'SRD', name: 'Surinamese Dollar', symbol: '$', country: 'SR', flag: '/assets/images/flags/sr.png' },
  { code: 'GYD', name: 'Guyanese Dollar', symbol: 'G$', country: 'GY', flag: '/assets/images/flags/gy.png' },
  { code: 'BWP', name: 'Botswana Pula', symbol: 'P', country: 'BW', flag: '/assets/images/flags/bw.png' },
  { code: 'SZL', name: 'Swazi Lilangeni', symbol: 'E', country: 'SZ', flag: '/assets/images/flags/sz.png' },
  { code: 'LSL', name: 'Lesotho Loti', symbol: 'L', country: 'LS', flag: '/assets/images/flags/ls.png' },
  { code: 'NAD', name: 'Namibian Dollar', symbol: 'N$', country: 'NA', flag: '/assets/images/flags/na.png' },
  { code: 'ZMW', name: 'Zambian Kwacha', symbol: 'ZK', country: 'ZM', flag: '/assets/images/flags/zm.png' },
  { code: 'MWK', name: 'Malawian Kwacha', symbol: 'MK', country: 'MW', flag: '/assets/images/flags/mw.png' },
  { code: 'MZN', name: 'Mozambican Metical', symbol: 'MT', country: 'MZ', flag: '/assets/images/flags/mz.png' },
  { code: 'AOA', name: 'Angolan Kwanza', symbol: 'Kz', country: 'AO', flag: '/assets/images/flags/ao.png' },
  { code: 'MGA', name: 'Malagasy Ariary', symbol: 'Ar', country: 'MG', flag: '/assets/images/flags/mg.png' },
  { code: 'MUR', name: 'Mauritian Rupee', symbol: '₨', country: 'MU', flag: '/assets/images/flags/mu.png' },
  { code: 'SCR', name: 'Seychellois Rupee', symbol: '₨', country: 'SC', flag: '/assets/images/flags/sc.png' },
  { code: 'KMF', name: 'Comorian Franc', symbol: 'CF', country: 'KM', flag: '/assets/images/flags/km.png' },
  { code: 'DJF', name: 'Djiboutian Franc', symbol: 'Fdj', country: 'DJ', flag: '/assets/images/flags/dj.png' },
  { code: 'SOS', name: 'Somali Shilling', symbol: 'S', country: 'SO', flag: '/assets/images/flags/so.png' },
  { code: 'ERN', name: 'Eritrean Nakfa', symbol: 'Nfk', country: 'ER', flag: '/assets/images/flags/er.png' },
  { code: 'SSP', name: 'South Sudanese Pound', symbol: '£', country: 'SS', flag: '/assets/images/flags/ss.png' },
  { code: 'CDF', name: 'Congolese Franc', symbol: 'FC', country: 'CD', flag: '/assets/images/flags/cd.png' },
  { code: 'RWF', name: 'Rwandan Franc', symbol: 'RF', country: 'RW', flag: '/assets/images/flags/rw.png' },
  { code: 'BIF', name: 'Burundian Franc', symbol: 'FBu', country: 'BI', flag: '/assets/images/flags/bi.png' },
  { code: 'CVE', name: 'Cape Verdean Escudo', symbol: '$', country: 'CV', flag: '/assets/images/flags/cv.png' },
  { code: 'STN', name: 'Sao Tomean Dobra', symbol: 'Db', country: 'ST', flag: '/assets/images/flags/st.png' },
  { code: 'GMD', name: 'Gambian Dalasi', symbol: 'D', country: 'GM', flag: '/assets/images/flags/gm.png' },
  { code: 'GNF', name: 'Guinean Franc', symbol: 'FG', country: 'GN', flag: '/assets/images/flags/gn.png' },
  { code: 'SLL', name: 'Sierra Leonean Leone', symbol: 'Le', country: 'SL', flag: '/assets/images/flags/sl.png' },
  { code: 'LRD', name: 'Liberian Dollar', symbol: 'L$', country: 'LR', flag: '/assets/images/flags/lr.png' },
  { code: 'GIP', name: 'Gibraltar Pound', symbol: '£', country: 'GI', flag: '/assets/images/flags/gi.png' },
  { code: 'FKP', name: 'Falkland Islands Pound', symbol: '£', country: 'FK', flag: '/assets/images/flags/fk.png' },
  { code: 'SHP', name: 'Saint Helena Pound', symbol: '£', country: 'SH', flag: '/assets/images/flags/sh.png' },
  { code: 'AZN', name: 'Azerbaijani Manat', symbol: '₼', country: 'AZ', flag: '/assets/images/flags/az.png' },
  { code: 'GEL', name: 'Georgian Lari', symbol: '₾', country: 'GE', flag: '/assets/images/flags/ge.png' },
  { code: 'KZT', name: 'Kazakhstani Tenge', symbol: '₸', country: 'KZ', flag: '/assets/images/flags/kz.png' },
  { code: 'KGS', name: 'Kyrgyzstani Som', symbol: 'с', country: 'KG', flag: '/assets/images/flags/kg.png' },
  { code: 'TJS', name: 'Tajikistani Somoni', symbol: 'SM', country: 'TJ', flag: '/assets/images/flags/tj.png' },
  { code: 'TMT', name: 'Turkmenistani Manat', symbol: 'T', country: 'TM', flag: '/assets/images/flags/tm.png' },
  { code: 'UZS', name: 'Uzbekistani Som', symbol: 'лв', country: 'UZ', flag: '/assets/images/flags/uz.png' },
  { code: 'MNT', name: 'Mongolian Tugrik', symbol: '₮', country: 'MN', flag: '/assets/images/flags/mn.png' },
  { code: 'AFN', name: 'Afghan Afghani', symbol: '؋', country: 'AF', flag: '/assets/images/flags/af.png' },
  { code: 'BDT', name: 'Bangladeshi Taka', symbol: '৳', country: 'BD', flag: '/assets/images/flags/bd.png' },
  { code: 'BTN', name: 'Bhutanese Ngultrum', symbol: 'Nu.', country: 'BT', flag: '/assets/images/flags/bt.png' },
  { code: 'NPR', name: 'Nepalese Rupee', symbol: '₨', country: 'NP', flag: '/assets/images/flags/np.png' },
  { code: 'LKR', name: 'Sri Lankan Rupee', symbol: '₨', country: 'LK', flag: '/assets/images/flags/lk.png' },
  { code: 'MVR', name: 'Maldivian Rufiyaa', symbol: 'Rf', country: 'MV', flag: '/assets/images/flags/mv.png' },
  { code: 'IDR', name: 'Indonesian Rupiah', symbol: 'Rp', country: 'ID', flag: '/assets/images/flags/id.png' },
  { code: 'VND', name: 'Vietnamese Dong', symbol: '₫', country: 'VN', flag: '/assets/images/flags/vn.png' },
  { code: 'LAK', name: 'Lao Kip', symbol: '₭', country: 'LA', flag: '/assets/images/flags/la.png' },
  { code: 'KHR', name: 'Cambodian Riel', symbol: '៛', country: 'KH', flag: '/assets/images/flags/kh.png' },
  { code: 'MMK', name: 'Myanmar Kyat', symbol: 'K', country: 'MM', flag: '/assets/images/flags/mm.png' },
  { code: 'BND', name: 'Brunei Dollar', symbol: 'B$', country: 'BN', flag: '/assets/images/flags/bn.png' },
  { code: 'FJD', name: 'Fijian Dollar', symbol: 'FJ$', country: 'FJ', flag: '/assets/images/flags/fj.png' },
  { code: 'PGK', name: 'Papua New Guinean Kina', symbol: 'K', country: 'PG', flag: '/assets/images/flags/pg.png' },
  { code: 'SBD', name: 'Solomon Islands Dollar', symbol: 'SI$', country: 'SB', flag: '/assets/images/flags/sb.png' },
  { code: 'VUV', name: 'Vanuatu Vatu', symbol: 'Vt', country: 'VU', flag: '/assets/images/flags/vu.png' },
  { code: 'WST', name: 'Samoan Tala', symbol: 'WS$', country: 'WS', flag: '/assets/images/flags/ws.png' },
  { code: 'TOP', name: 'Tongan Pa\'anga', symbol: 'T$', country: 'TO', flag: '/assets/images/flags/to.png' },
  { code: 'XPF', name: 'CFP Franc', symbol: '₣', country: 'XPF', flag: '/assets/images/flags/pf.png' }
];

export const COUNTRY_CURRENCY_MAP = {
  'US': 'USD', 'CA': 'CAD', 'MX': 'MXN', 'GT': 'GTQ', 'HN': 'HNL', 'NI': 'NIO', 'CR': 'CRC', 'PA': 'PAB', 'DO': 'DOP', 'JM': 'JMD', 'TT': 'TTD', 'BB': 'BBD', 'BZ': 'BZD', 'AW': 'AWG', 'AN': 'ANG', 'SR': 'SRD', 'GY': 'GYD',
  'GB': 'GBP', 'IE': 'EUR', 'FR': 'EUR', 'DE': 'EUR', 'IT': 'EUR', 'ES': 'EUR', 'PT': 'EUR', 'NL': 'EUR', 'BE': 'EUR', 'AT': 'EUR', 'FI': 'EUR', 'LU': 'EUR', 'MT': 'EUR', 'CY': 'EUR', 'SI': 'EUR', 'SK': 'EUR', 'EE': 'EUR', 'LV': 'EUR', 'LT': 'EUR',
  'JP': 'JPY', 'CN': 'CNY', 'KR': 'KRW', 'TW': 'TWD', 'TH': 'THB', 'MY': 'MYR', 'SG': 'SGD', 'PH': 'PHP', 'ID': 'IDR', 'VN': 'VND', 'LA': 'LAK', 'KH': 'KHR', 'MM': 'MMK', 'BN': 'BND', 'MV': 'MVR', 'LK': 'LKR', 'NP': 'NPR', 'BT': 'BTN', 'BD': 'BDT', 'AF': 'AFN',
  'AU': 'AUD', 'NZ': 'NZD', 'FJ': 'FJD', 'PG': 'PGK', 'SB': 'SBD', 'VU': 'VUV', 'WS': 'WST', 'TO': 'TOP', 'KI': 'AUD', 'TV': 'AUD', 'NR': 'AUD', 'PW': 'USD', 'FM': 'USD', 'MH': 'USD', 'MP': 'USD', 'GU': 'USD', 'AS': 'USD', 'VI': 'USD', 'PR': 'USD',
  'RU': 'RUB', 'UA': 'UAH', 'BY': 'BYN', 'MD': 'MDL', 'AM': 'AMD', 'AZ': 'AZN', 'GE': 'GEL', 'KZ': 'KZT', 'KG': 'KGS', 'TJ': 'TJS', 'TM': 'TMT', 'UZ': 'UZS', 'MN': 'MNT',
  'TR': 'TRY', 'PS': 'ILS', 'JO': 'JOD', 'LB': 'LBP', 'SY': 'SYP', 'IQ': 'IQD', 'IR': 'IRR', 'SA': 'SAR', 'AE': 'AED', 'QA': 'QAR', 'KW': 'KWD', 'BH': 'BHD', 'OM': 'OMR', 'YE': 'YER',
  'EG': 'EGP', 'LY': 'LYD', 'TN': 'TND', 'DZ': 'DZD', 'MA': 'MAD', 'SD': 'SDG', 'SS': 'SSP', 'ET': 'ETB', 'ER': 'ERN', 'DJ': 'DJF', 'SO': 'SOS', 'KE': 'KES', 'UG': 'UGX', 'TZ': 'TZS', 'RW': 'RWF', 'BI': 'BIF', 'CD': 'CDF', 'CF': 'XAF', 'TD': 'XAF', 'CM': 'XAF', 'GQ': 'XAF', 'GA': 'XAF', 'ST': 'STN', 'CV': 'CVE', 'GW': 'XOF', 'GN': 'GNF', 'SL': 'SLL', 'LR': 'LRD', 'SN': 'XOF', 'ML': 'XOF', 'BF': 'XOF', 'NE': 'XOF', 'CI': 'XOF', 'GH': 'GHS', 'TG': 'XOF', 'BJ': 'XOF', 'NG': 'NGN', 'GM': 'GMD', 'GN': 'GNF', 'GW': 'XOF', 'SL': 'SLL', 'LR': 'LRD', 'SN': 'XOF', 'ML': 'XOF', 'BF': 'XOF', 'NE': 'XOF', 'CI': 'XOF', 'GH': 'GHS', 'TG': 'XOF', 'BJ': 'XOF',
  'ZA': 'ZAR', 'BW': 'BWP', 'SZ': 'SZL', 'LS': 'LSL', 'NA': 'NAD', 'ZM': 'ZMW', 'ZW': 'ZWL', 'MW': 'MWK', 'MZ': 'MZN', 'AO': 'AOA', 'MG': 'MGA', 'MU': 'MUR', 'SC': 'SCR', 'KM': 'KMF', 'YT': 'EUR', 'RE': 'EUR', 'SH': 'SHP', 'AC': 'SHP', 'TA': 'SHP',
  'BR': 'BRL', 'AR': 'ARS', 'UY': 'UYU', 'BO': 'BOB', 'PE': 'PEN', 'CO': 'COP', 'VE': 'VES', 'GY': 'GYD', 'SR': 'SRD', 'PY': 'PYG', 'CL': 'CLP', 'EC': 'USD', 'FK': 'FKP', 'GF': 'EUR', 'GP': 'EUR', 'MQ': 'EUR', 'PM': 'EUR', 'BL': 'EUR', 'MF': 'EUR', 'SX': 'ANG', 'CW': 'ANG', 'BQ': 'USD', 'AW': 'AWG', 'AN': 'ANG', 'SR': 'SRD', 'GY': 'GYD', 'TT': 'TTD', 'BB': 'BBD', 'BZ': 'BZD', 'JM': 'JMD', 'HT': 'HTG', 'CU': 'CUP', 'DO': 'DOP', 'PR': 'USD', 'VI': 'USD', 'AG': 'XCD', 'DM': 'XCD', 'GD': 'XCD', 'KN': 'XCD', 'LC': 'XCD', 'VC': 'XCD', 'AI': 'XCD', 'MS': 'XCD', 'TC': 'USD', 'VG': 'USD', 'KY': 'KYD', 'BM': 'BMD', 'BS': 'BSD', 'TC': 'USD', 'VG': 'USD', 'KY': 'KYD', 'BM': 'BMD', 'BS': 'BSD'
};

export const getCurrencyByCountry = (countryCode) => {
  return COUNTRY_CURRENCY_MAP[countryCode] || 'AMD';
};

export const getCurrencyByCode = (currencyCode) => {
  return CURRENCIES.find(currency => currency.code === currencyCode) || CURRENCIES[0];
};
