export const CURRENCIES = [
  { code: 'USD', name: 'US Dollar', symbol: '$', country: 'US' },
  { code: 'EUR', name: 'Euro', symbol: '€', country: 'EU' },
  { code: 'GBP', name: 'British Pound', symbol: '£', country: 'GB' },
  { code: 'JPY', name: 'Japanese Yen', symbol: '¥', country: 'JP' },
  { code: 'CAD', name: 'Canadian Dollar', symbol: 'C$', country: 'CA' },
  { code: 'AUD', name: 'Australian Dollar', symbol: 'A$', country: 'AU' },
  { code: 'CHF', name: 'Swiss Franc', symbol: 'CHF', country: 'CH' },
  { code: 'CNY', name: 'Chinese Yuan', symbol: '¥', country: 'CN' },
  { code: 'SEK', name: 'Swedish Krona', symbol: 'kr', country: 'SE' },
  { code: 'NZD', name: 'New Zealand Dollar', symbol: 'NZ$', country: 'NZ' },
  { code: 'MXN', name: 'Mexican Peso', symbol: '$', country: 'MX' },
  { code: 'SGD', name: 'Singapore Dollar', symbol: 'S$', country: 'SG' },
  { code: 'HKD', name: 'Hong Kong Dollar', symbol: 'HK$', country: 'HK' },
  { code: 'NOK', name: 'Norwegian Krone', symbol: 'kr', country: 'NO' },
  { code: 'TRY', name: 'Turkish Lira', symbol: '₺', country: 'TR' },
  { code: 'RUB', name: 'Russian Ruble', symbol: '₽', country: 'RU' },
  { code: 'INR', name: 'Indian Rupee', symbol: '₹', country: 'IN' },
  { code: 'BRL', name: 'Brazilian Real', symbol: 'R$', country: 'BR' },
  { code: 'ZAR', name: 'South African Rand', symbol: 'R', country: 'ZA' },
  { code: 'KRW', name: 'South Korean Won', symbol: '₩', country: 'KR' },
  { code: 'DKK', name: 'Danish Krone', symbol: 'kr', country: 'DK' },
  { code: 'PLN', name: 'Polish Zloty', symbol: 'zł', country: 'PL' },
  { code: 'TWD', name: 'Taiwan Dollar', symbol: 'NT$', country: 'TW' },
  { code: 'THB', name: 'Thai Baht', symbol: '฿', country: 'TH' },
  { code: 'MYR', name: 'Malaysian Ringgit', symbol: 'RM', country: 'MY' },
  { code: 'PHP', name: 'Philippine Peso', symbol: '₱', country: 'PH' },
  { code: 'CZK', name: 'Czech Koruna', symbol: 'Kč', country: 'CZ' },
  { code: 'HUF', name: 'Hungarian Forint', symbol: 'Ft', country: 'HU' },
  { code: 'ILS', name: 'Israeli Shekel', symbol: '₪', country: 'IL' },
  { code: 'CLP', name: 'Chilean Peso', symbol: '$', country: 'CL' },
  { code: 'PKR', name: 'Pakistani Rupee', symbol: '₨', country: 'PK' },
  { code: 'BGN', name: 'Bulgarian Lev', symbol: 'лв', country: 'BG' },
  { code: 'RON', name: 'Romanian Leu', symbol: 'lei', country: 'RO' },
  { code: 'HRK', name: 'Croatian Kuna', symbol: 'kn', country: 'HR' },
  { code: 'ISK', name: 'Icelandic Krona', symbol: 'kr', country: 'IS' },
  { code: 'UAH', name: 'Ukrainian Hryvnia', symbol: '₴', country: 'UA' },
  { code: 'AED', name: 'UAE Dirham', symbol: 'د.إ', country: 'AE' },
  { code: 'SAR', name: 'Saudi Riyal', symbol: '﷼', country: 'SA' },
  { code: 'QAR', name: 'Qatari Riyal', symbol: '﷼', country: 'QA' },
  { code: 'KWD', name: 'Kuwaiti Dinar', symbol: 'د.ك', country: 'KW' },
  { code: 'BHD', name: 'Bahraini Dinar', symbol: 'د.ب', country: 'BH' },
  { code: 'OMR', name: 'Omani Rial', symbol: '﷼', country: 'OM' },
  { code: 'JOD', name: 'Jordanian Dinar', symbol: 'د.ا', country: 'JO' },
  { code: 'LBP', name: 'Lebanese Pound', symbol: 'ل.ل', country: 'LB' },
  { code: 'EGP', name: 'Egyptian Pound', symbol: '£', country: 'EG' },
  { code: 'MAD', name: 'Moroccan Dirham', symbol: 'د.م.', country: 'MA' },
  { code: 'TND', name: 'Tunisian Dinar', symbol: 'د.ت', country: 'TN' },
  { code: 'DZD', name: 'Algerian Dinar', symbol: 'د.ج', country: 'DZ' },
  { code: 'LYD', name: 'Libyan Dinar', symbol: 'ل.د', country: 'LY' },
  { code: 'ETB', name: 'Ethiopian Birr', symbol: 'Br', country: 'ET' },
  { code: 'KES', name: 'Kenyan Shilling', symbol: 'KSh', country: 'KE' },
  { code: 'UGX', name: 'Ugandan Shilling', symbol: 'USh', country: 'UG' },
  { code: 'TZS', name: 'Tanzanian Shilling', symbol: 'TSh', country: 'TZ' },
  { code: 'NGN', name: 'Nigerian Naira', symbol: '₦', country: 'NG' },
  { code: 'GHS', name: 'Ghanaian Cedi', symbol: '₵', country: 'GH' },
  { code: 'XOF', name: 'West African CFA Franc', symbol: 'CFA', country: 'XOF' },
  { code: 'XAF', name: 'Central African CFA Franc', symbol: 'FCFA', country: 'XAF' },
  { code: 'ARS', name: 'Argentine Peso', symbol: '$', country: 'AR' },
  { code: 'UYU', name: 'Uruguayan Peso', symbol: '$U', country: 'UY' },
  { code: 'BOB', name: 'Bolivian Boliviano', symbol: 'Bs', country: 'BO' },
  { code: 'PEN', name: 'Peruvian Sol', symbol: 'S/', country: 'PE' },
  { code: 'COP', name: 'Colombian Peso', symbol: '$', country: 'CO' },
  { code: 'VES', name: 'Venezuelan Bolivar', symbol: 'Bs.S', country: 'VE' },
  { code: 'GTQ', name: 'Guatemalan Quetzal', symbol: 'Q', country: 'GT' },
  { code: 'HNL', name: 'Honduran Lempira', symbol: 'L', country: 'HN' },
  { code: 'NIO', name: 'Nicaraguan Cordoba', symbol: 'C$', country: 'NI' },
  { code: 'CRC', name: 'Costa Rican Colon', symbol: '₡', country: 'CR' },
  { code: 'PAB', name: 'Panamanian Balboa', symbol: 'B/.', country: 'PA' },
  { code: 'DOP', name: 'Dominican Peso', symbol: 'RD$', country: 'DO' },
  { code: 'JMD', name: 'Jamaican Dollar', symbol: 'J$', country: 'JM' },
  { code: 'TTD', name: 'Trinidad and Tobago Dollar', symbol: 'TT$', country: 'TT' },
  { code: 'BBD', name: 'Barbadian Dollar', symbol: 'Bds$', country: 'BB' },
  { code: 'BZD', name: 'Belize Dollar', symbol: 'BZ$', country: 'BZ' },
  { code: 'XCD', name: 'East Caribbean Dollar', symbol: 'EC$', country: 'XCD' },
  { code: 'AWG', name: 'Aruban Florin', symbol: 'ƒ', country: 'AW' },
  { code: 'ANG', name: 'Netherlands Antillean Guilder', symbol: 'ƒ', country: 'AN' },
  { code: 'SRD', name: 'Surinamese Dollar', symbol: '$', country: 'SR' },
  { code: 'GYD', name: 'Guyanese Dollar', symbol: 'G$', country: 'GY' },
  { code: 'BWP', name: 'Botswana Pula', symbol: 'P', country: 'BW' },
  { code: 'SZL', name: 'Swazi Lilangeni', symbol: 'E', country: 'SZ' },
  { code: 'LSL', name: 'Lesotho Loti', symbol: 'L', country: 'LS' },
  { code: 'NAD', name: 'Namibian Dollar', symbol: 'N$', country: 'NA' },
  { code: 'ZMW', name: 'Zambian Kwacha', symbol: 'ZK', country: 'ZM' },
  { code: 'MWK', name: 'Malawian Kwacha', symbol: 'MK', country: 'MW' },
  { code: 'MZN', name: 'Mozambican Metical', symbol: 'MT', country: 'MZ' },
  { code: 'AOA', name: 'Angolan Kwanza', symbol: 'Kz', country: 'AO' },
  { code: 'MGA', name: 'Malagasy Ariary', symbol: 'Ar', country: 'MG' },
  { code: 'MUR', name: 'Mauritian Rupee', symbol: '₨', country: 'MU' },
  { code: 'SCR', name: 'Seychellois Rupee', symbol: '₨', country: 'SC' },
  { code: 'KMF', name: 'Comorian Franc', symbol: 'CF', country: 'KM' },
  { code: 'DJF', name: 'Djiboutian Franc', symbol: 'Fdj', country: 'DJ' },
  { code: 'SOS', name: 'Somali Shilling', symbol: 'S', country: 'SO' },
  { code: 'ERN', name: 'Eritrean Nakfa', symbol: 'Nfk', country: 'ER' },
  { code: 'SSP', name: 'South Sudanese Pound', symbol: '£', country: 'SS' },
  { code: 'CDF', name: 'Congolese Franc', symbol: 'FC', country: 'CD' },
  { code: 'RWF', name: 'Rwandan Franc', symbol: 'RF', country: 'RW' },
  { code: 'BIF', name: 'Burundian Franc', symbol: 'FBu', country: 'BI' },
  { code: 'CVE', name: 'Cape Verdean Escudo', symbol: '$', country: 'CV' },
  { code: 'STN', name: 'Sao Tomean Dobra', symbol: 'Db', country: 'ST' },
  { code: 'GMD', name: 'Gambian Dalasi', symbol: 'D', country: 'GM' },
  { code: 'GNF', name: 'Guinean Franc', symbol: 'FG', country: 'GN' },
  { code: 'SLL', name: 'Sierra Leonean Leone', symbol: 'Le', country: 'SL' },
  { code: 'LRD', name: 'Liberian Dollar', symbol: 'L$', country: 'LR' },
  { code: 'GIP', name: 'Gibraltar Pound', symbol: '£', country: 'GI' },
  { code: 'FKP', name: 'Falkland Islands Pound', symbol: '£', country: 'FK' },
  { code: 'SHP', name: 'Saint Helena Pound', symbol: '£', country: 'SH' },
  { code: 'AMD', name: 'Armenian Dram', symbol: '֏', country: 'AM' },
  { code: 'AZN', name: 'Azerbaijani Manat', symbol: '₼', country: 'AZ' },
  { code: 'GEL', name: 'Georgian Lari', symbol: '₾', country: 'GE' },
  { code: 'KZT', name: 'Kazakhstani Tenge', symbol: '₸', country: 'KZ' },
  { code: 'KGS', name: 'Kyrgyzstani Som', symbol: 'с', country: 'KG' },
  { code: 'TJS', name: 'Tajikistani Somoni', symbol: 'SM', country: 'TJ' },
  { code: 'TMT', name: 'Turkmenistani Manat', symbol: 'T', country: 'TM' },
  { code: 'UZS', name: 'Uzbekistani Som', symbol: 'лв', country: 'UZ' },
  { code: 'MNT', name: 'Mongolian Tugrik', symbol: '₮', country: 'MN' },
  { code: 'AFN', name: 'Afghan Afghani', symbol: '؋', country: 'AF' },
  { code: 'BDT', name: 'Bangladeshi Taka', symbol: '৳', country: 'BD' },
  { code: 'BTN', name: 'Bhutanese Ngultrum', symbol: 'Nu.', country: 'BT' },
  { code: 'NPR', name: 'Nepalese Rupee', symbol: '₨', country: 'NP' },
  { code: 'LKR', name: 'Sri Lankan Rupee', symbol: '₨', country: 'LK' },
  { code: 'MVR', name: 'Maldivian Rufiyaa', symbol: 'Rf', country: 'MV' },
  { code: 'IDR', name: 'Indonesian Rupiah', symbol: 'Rp', country: 'ID' },
  { code: 'VND', name: 'Vietnamese Dong', symbol: '₫', country: 'VN' },
  { code: 'LAK', name: 'Lao Kip', symbol: '₭', country: 'LA' },
  { code: 'KHR', name: 'Cambodian Riel', symbol: '៛', country: 'KH' },
  { code: 'MMK', name: 'Myanmar Kyat', symbol: 'K', country: 'MM' },
  { code: 'BND', name: 'Brunei Dollar', symbol: 'B$', country: 'BN' },
  { code: 'FJD', name: 'Fijian Dollar', symbol: 'FJ$', country: 'FJ' },
  { code: 'PGK', name: 'Papua New Guinean Kina', symbol: 'K', country: 'PG' },
  { code: 'SBD', name: 'Solomon Islands Dollar', symbol: 'SI$', country: 'SB' },
  { code: 'VUV', name: 'Vanuatu Vatu', symbol: 'Vt', country: 'VU' },
  { code: 'WST', name: 'Samoan Tala', symbol: 'WS$', country: 'WS' },
  { code: 'TOP', name: 'Tongan Pa\'anga', symbol: 'T$', country: 'TO' },
  { code: 'XPF', name: 'CFP Franc', symbol: '₣', country: 'XPF' }
];

// Country to currency mapping for geolocation
export const COUNTRY_CURRENCY_MAP = {
  'US': 'USD', 'CA': 'CAD', 'MX': 'MXN', 'GT': 'GTQ', 'HN': 'HNL', 'NI': 'NIO', 'CR': 'CRC', 'PA': 'PAB', 'DO': 'DOP', 'JM': 'JMD', 'TT': 'TTD', 'BB': 'BBD', 'BZ': 'BZD', 'AW': 'AWG', 'AN': 'ANG', 'SR': 'SRD', 'GY': 'GYD',
  'GB': 'GBP', 'IE': 'EUR', 'FR': 'EUR', 'DE': 'EUR', 'IT': 'EUR', 'ES': 'EUR', 'PT': 'EUR', 'NL': 'EUR', 'BE': 'EUR', 'AT': 'EUR', 'FI': 'EUR', 'LU': 'EUR', 'MT': 'EUR', 'CY': 'EUR', 'SI': 'EUR', 'SK': 'EUR', 'EE': 'EUR', 'LV': 'EUR', 'LT': 'EUR',
  'JP': 'JPY', 'CN': 'CNY', 'KR': 'KRW', 'TW': 'TWD', 'TH': 'THB', 'MY': 'MYR', 'SG': 'SGD', 'PH': 'PHP', 'ID': 'IDR', 'VN': 'VND', 'LA': 'LAK', 'KH': 'KHR', 'MM': 'MMK', 'BN': 'BND', 'MV': 'MVR', 'LK': 'LKR', 'NP': 'NPR', 'BT': 'BTN', 'BD': 'BDT', 'AF': 'AFN',
  'AU': 'AUD', 'NZ': 'NZD', 'FJ': 'FJD', 'PG': 'PGK', 'SB': 'SBD', 'VU': 'VUV', 'WS': 'WST', 'TO': 'TOP', 'KI': 'AUD', 'TV': 'AUD', 'NR': 'AUD', 'PW': 'USD', 'FM': 'USD', 'MH': 'USD', 'MP': 'USD', 'GU': 'USD', 'AS': 'USD', 'VI': 'USD', 'PR': 'USD',
  'RU': 'RUB', 'UA': 'UAH', 'BY': 'BYN', 'MD': 'MDL', 'AM': 'AMD', 'AZ': 'AZN', 'GE': 'GEL', 'KZ': 'KZT', 'KG': 'KGS', 'TJ': 'TJS', 'TM': 'TMT', 'UZ': 'UZS', 'MN': 'MNT',
  'TR': 'TRY', 'IL': 'ILS', 'JO': 'JOD', 'LB': 'LBP', 'SY': 'SYP', 'IQ': 'IQD', 'IR': 'IRR', 'SA': 'SAR', 'AE': 'AED', 'QA': 'QAR', 'KW': 'KWD', 'BH': 'BHD', 'OM': 'OMR', 'YE': 'YER',
  'EG': 'EGP', 'LY': 'LYD', 'TN': 'TND', 'DZ': 'DZD', 'MA': 'MAD', 'SD': 'SDG', 'SS': 'SSP', 'ET': 'ETB', 'ER': 'ERN', 'DJ': 'DJF', 'SO': 'SOS', 'KE': 'KES', 'UG': 'UGX', 'TZ': 'TZS', 'RW': 'RWF', 'BI': 'BIF', 'CD': 'CDF', 'CF': 'XAF', 'TD': 'XAF', 'CM': 'XAF', 'GQ': 'XAF', 'GA': 'XAF', 'ST': 'STN', 'CV': 'CVE', 'GW': 'XOF', 'GN': 'GNF', 'SL': 'SLL', 'LR': 'LRD', 'SN': 'XOF', 'ML': 'XOF', 'BF': 'XOF', 'NE': 'XOF', 'CI': 'XOF', 'GH': 'GHS', 'TG': 'XOF', 'BJ': 'XOF', 'NG': 'NGN', 'GM': 'GMD', 'GN': 'GNF', 'GW': 'XOF', 'SL': 'SLL', 'LR': 'LRD', 'SN': 'XOF', 'ML': 'XOF', 'BF': 'XOF', 'NE': 'XOF', 'CI': 'XOF', 'GH': 'GHS', 'TG': 'XOF', 'BJ': 'XOF',
  'ZA': 'ZAR', 'BW': 'BWP', 'SZ': 'SZL', 'LS': 'LSL', 'NA': 'NAD', 'ZM': 'ZMW', 'ZW': 'ZWL', 'MW': 'MWK', 'MZ': 'MZN', 'AO': 'AOA', 'MG': 'MGA', 'MU': 'MUR', 'SC': 'SCR', 'KM': 'KMF', 'YT': 'EUR', 'RE': 'EUR', 'SH': 'SHP', 'AC': 'SHP', 'TA': 'SHP',
  'BR': 'BRL', 'AR': 'ARS', 'UY': 'UYU', 'BO': 'BOB', 'PE': 'PEN', 'CO': 'COP', 'VE': 'VES', 'GY': 'GYD', 'SR': 'SRD', 'PY': 'PYG', 'CL': 'CLP', 'EC': 'USD', 'FK': 'FKP', 'GF': 'EUR', 'GP': 'EUR', 'MQ': 'EUR', 'PM': 'EUR', 'BL': 'EUR', 'MF': 'EUR', 'SX': 'ANG', 'CW': 'ANG', 'BQ': 'USD', 'AW': 'AWG', 'AN': 'ANG', 'SR': 'SRD', 'GY': 'GYD', 'TT': 'TTD', 'BB': 'BBD', 'BZ': 'BZD', 'JM': 'JMD', 'HT': 'HTG', 'CU': 'CUP', 'DO': 'DOP', 'PR': 'USD', 'VI': 'USD', 'AG': 'XCD', 'DM': 'XCD', 'GD': 'XCD', 'KN': 'XCD', 'LC': 'XCD', 'VC': 'XCD', 'AI': 'XCD', 'MS': 'XCD', 'TC': 'USD', 'VG': 'USD', 'KY': 'KYD', 'BM': 'BMD', 'BS': 'BSD', 'TC': 'USD', 'VG': 'USD', 'KY': 'KYD', 'BM': 'BMD', 'BS': 'BSD'
};

// Get currency by country code
export const getCurrencyByCountry = (countryCode) => {
  return COUNTRY_CURRENCY_MAP[countryCode] || 'USD';
};

// Get currency object by code
export const getCurrencyByCode = (currencyCode) => {
  return CURRENCIES.find(currency => currency.code === currencyCode) || CURRENCIES[0];
};
