import { Inter } from "next/font/google";
import "./globals.css";
import { StoreProvider } from "@/context/store-context";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "My Next.js App",
  description: "Generated by v0",
  generator: "v0.dev",
};

export default async function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <StoreProvider>{children}</StoreProvider>
      </body>
    </html>
  );
}
